package PRINCIPAL;

import CODIGOINTERNO.CIFuncionario;
import CODIGOINTERNO.CIRegistro;
import JANELA.Janelas;
import java.sql.Connection;
import CONEXAO.Conexao;
import VARIAVEIS.Cliente;
import VARIAVEIS.DataHora;
import VARIAVEIS.Funcionario;
import VARIAVEIS.Registro;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {

    private Connection conexao;
    Janelas abreJanela;
    DataHora dh = new DataHora();
    CIRegistro reg = new CIRegistro();
    Registro r = new Registro();
    Funcionario fun = new Funcionario();
    CIFuncionario cif = new CIFuncionario();
    Cliente c = new Cliente();
    static String cpfAutor;

    public FrmPrincipal() {
        initComponents();
        this.abreJanela = new Janelas(dkpPrincipal);
        this.conexao = new Conexao().getConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpPrincipal = new javax.swing.JDesktopPane();
        pnlLogin = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JToggleButton();
        btnLogoff = new javax.swing.JToggleButton();
        lblAviso = new javax.swing.JLabel();
        chbVisualiza = new javax.swing.JCheckBox();
        mnbFerramentas = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mniCliente = new javax.swing.JMenuItem();
        mnuReserva = new javax.swing.JMenu();
        mniReserva = new javax.swing.JMenuItem();
        mnuAdmin = new javax.swing.JMenu();
        mniFuncionarios = new javax.swing.JMenuItem();
        mniAdministracao = new javax.swing.JMenuItem();
        mniRegistro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - Restaurante");
        setBackground(new java.awt.Color(153, 153, 153));
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dkpPrincipal.setBackground(new java.awt.Color(0, 102, 0));
        dkpPrincipal.setMinimumSize(new java.awt.Dimension(1000, 800));

        pnlLogin.setBackground(new java.awt.Color(204, 51, 0));
        pnlLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Login de usuários:"));

        lblCpf.setText("Cpf:");

        lblSenha.setText("Senha:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Login.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Logoff.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        chbVisualiza.setText("Visualizar");
        chbVisualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbVisualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlLoginLayout.createSequentialGroup()
                                        .addComponent(lblCpf)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCpf))
                                    .addGroup(pnlLoginLayout.createSequentialGroup()
                                        .addComponent(lblSenha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbVisualiza)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnLogoff)))
                        .addGap(20, 20, 20))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbVisualiza))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLogoff))
                .addGap(18, 18, 18)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dkpPrincipalLayout = new javax.swing.GroupLayout(dkpPrincipal);
        dkpPrincipal.setLayout(dkpPrincipalLayout);
        dkpPrincipalLayout.setHorizontalGroup(
            dkpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpPrincipalLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dkpPrincipalLayout.setVerticalGroup(
            dkpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkpPrincipalLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dkpPrincipal.setLayer(pnlLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mnbFerramentas.setName(""); // NOI18N

        mnuCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/cadastro.png"))); // NOI18N
        mnuCadastro.setText("Cadastro");
        mnuCadastro.setBorderPainted(true);
        mnuCadastro.setEnabled(false);

        mniCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/pessoa.png"))); // NOI18N
        mniCliente.setText("Clientes");
        mniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mniCliente);

        mnbFerramentas.add(mnuCadastro);

        mnuReserva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/reserva.png"))); // NOI18N
        mnuReserva.setText("Reserva");
        mnuReserva.setBorderPainted(true);
        mnuReserva.setEnabled(false);

        mniReserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mniReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/nova.png"))); // NOI18N
        mniReserva.setText("Reserva");
        mniReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReservaActionPerformed(evt);
            }
        });
        mnuReserva.add(mniReserva);

        mnbFerramentas.add(mnuReserva);

        mnuAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/admin.png"))); // NOI18N
        mnuAdmin.setText("Admin");
        mnuAdmin.setBorderPainted(true);
        mnuAdmin.setEnabled(false);

        mniFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/funcionario.png"))); // NOI18N
        mniFuncionarios.setText("Funcionários");
        mniFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFuncionariosActionPerformed(evt);
            }
        });
        mnuAdmin.add(mniFuncionarios);

        mniAdministracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniAdministracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Dados.png"))); // NOI18N
        mniAdministracao.setText("Dados da Administração");
        mniAdministracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdministracaoActionPerformed(evt);
            }
        });
        mnuAdmin.add(mniAdministracao);

        mniRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Registro.png"))); // NOI18N
        mniRegistro.setText("Registro de Atividades");
        mniRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRegistroActionPerformed(evt);
            }
        });
        mnuAdmin.add(mniRegistro);

        mnbFerramentas.add(mnuAdmin);

        setJMenuBar(mnbFerramentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClienteActionPerformed
        abreJanela.janelas(IfrmClientes.getInstancia());
    }//GEN-LAST:event_mniClienteActionPerformed

    private void mniReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReservaActionPerformed
        abreJanela.janelas(IfrmReserva.getInstancia());
    }//GEN-LAST:event_mniReservaActionPerformed

    private void mniFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFuncionariosActionPerformed
        abreJanela.janelas(IfrmFuncionarios.getInstancia());
    }//GEN-LAST:event_mniFuncionariosActionPerformed

    private void mniAdministracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdministracaoActionPerformed
        abreJanela.janelas(IfrmAdministracao.getInstancia());
    }//GEN-LAST:event_mniAdministracaoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String senha = new String(txtSenha.getPassword());
        loginSN();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Image icone = Toolkit.getDefaultToolkit().getImage("src/ICONES/Icone Principal.jpg");
        this.setIconImage(icone);
        fun.setLogado(false);
        registrarInicio();
    }//GEN-LAST:event_formWindowOpened

    private void mniRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRegistroActionPerformed
        abreJanela.janelas(IfrmRegistro.getInstancia());
    }//GEN-LAST:event_mniRegistroActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        if (fun.getLogado()) {
            registrarLogout();
            logoff();
        } else {
            lblAviso.setText("Nenhum usuário logado.");
        }
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        registrarFim();
    }//GEN-LAST:event_formWindowClosing

    private void chbVisualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbVisualizaActionPerformed
        if(chbVisualiza.isSelected()){
            txtSenha.setEchoChar((char)0);
        }
        else{
            txtSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_chbVisualizaActionPerformed

    private void logoff() {
        limpar();
        registrarLogout();
        cpfAutor = null;
        lblAviso.setText("Usuário deslogado.");
        fun.setLogado(false);
        mnuCadastro.setEnabled(false);
        mnuReserva.setEnabled(false);
        mnuAdmin.setEnabled(false);
        btnLogin.setEnabled(true);
    }

    private void loginSN() {
        String cpf = txtCpf.getText();
        String senha = new String(txtSenha.getPassword());
        cpfAutor = cpf;
        if (cif.pesquisarCpf(cpf) && cif.pesquisarSenha(senha,cpf)) {
            registrarLogin();
            JOptionPane.showMessageDialog(null, "Voce esta logado como: " + cpf, "LOGIN", JOptionPane.INFORMATION_MESSAGE);
            if (cif.pesquisarNivel(cpf).matches("0")) {
                mnuReserva.setEnabled(true);
            } else if (cif.pesquisarNivel(cpf).matches("1")) {
                mnuCadastro.setEnabled(true);
                mnuReserva.setEnabled(true);
            } else if (cif.pesquisarNivel(cpf).matches("2")) {
                mnuCadastro.setEnabled(true);
                mnuReserva.setEnabled(true);
                mnuAdmin.setEnabled(true);
            }
            limpar();
            fun.setLogado(true);
            btnLogin.setEnabled(false);

        } else {
            if (fun.getLogado() == false) {
                JOptionPane.showMessageDialog(null, "CPF ou Senha incorretos.\n"
                        + "Por favor tente novamente e insira os valores corretos.");
                r.setAcaoRegistro("Tentativa de login fracassada.");
                registrarTLogin();
            }
        }
    }

    private void limpar() {
        lblAviso.setText("");
        txtCpf.setText(null);
        txtSenha.setText(null);
    }
    
    private void preencherRegistro() {
        r.setCpfAutor(cpfAutor);
        r.setData(dh.getData());
        r.setHora(dh.getHora());
    }
    
    private void registrarInicio() {
        r.setAcaoRegistro("Sistema iniciado.");
        preencherRegistro();
        reg.registrar(r, dh);
    }
    private void registrarFim() {
        r.setAcaoRegistro("Sistema finalizado.");
        preencherRegistro();
        reg.registrar(r, dh);
    }

    private void registrarLogin() {
        r.setAcaoRegistro("Tentativa de login bem-sucedida.");
        preencherRegistro();
        reg.registrar(r, dh);
    }

    private void registrarTLogin() {
        r.setAcaoRegistro("Tentativa de login fracassada.");
        preencherRegistro();
        reg.registrar(r, dh);
    }

    private void registrarLogout() {
        r.setAcaoRegistro("Usuário efetuou o logout.");
        preencherRegistro();
        reg.registrar(r, dh);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JToggleButton btnLogoff;
    private javax.swing.JCheckBox chbVisualiza;
    private javax.swing.JDesktopPane dkpPrincipal;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JMenuBar mnbFerramentas;
    private javax.swing.JMenuItem mniAdministracao;
    private javax.swing.JMenuItem mniCliente;
    private javax.swing.JMenuItem mniFuncionarios;
    private javax.swing.JMenuItem mniRegistro;
    private javax.swing.JMenuItem mniReserva;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuReserva;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
