package PRINCIPAL;

import CODIGOINTERNO.CIFuncionario;
import CODIGOINTERNO.CIRegistro;
import VARIAVEIS.Funcionario;
import VARIAVEIS.Administracao;
import VARIAVEIS.DataHora;
import VARIAVEIS.Registro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IfrmFuncionarios extends javax.swing.JInternalFrame {

    private static IfrmFuncionarios ifrmFuncionarios;
    Registro r = new Registro();
    CIRegistro reg = new CIRegistro();
    DataHora dh = new DataHora();
    CIFuncionario cif = new CIFuncionario();
    Funcionario f = new Funcionario();

    public static IfrmFuncionarios getInstancia() {
        if (ifrmFuncionarios == null) {
            ifrmFuncionarios = new IfrmFuncionarios();
        }
        return ifrmFuncionarios;
    }

    public IfrmFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFuncionarios = new javax.swing.JPanel();
        pnlCadastroFuncionarios = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        cbxFuncao = new javax.swing.JComboBox();
        cbxNivel = new javax.swing.JComboBox();
        txtSalario = new javax.swing.JFormattedTextField();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        cbxDia = new javax.swing.JComboBox();
        cbxMes = new javax.swing.JComboBox();
        cbxAno = new javax.swing.JComboBox();
        txtHora = new javax.swing.JFormattedTextField();
        chbSenha = new javax.swing.JCheckBox();
        pnlTabelaFuncionarios = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        pnlFuncionarios.setBackground(new java.awt.Color(0, 255, 204));

        pnlCadastroFuncionarios.setBackground(new java.awt.Color(153, 255, 204));
        pnlCadastroFuncionarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de funcionários:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        lblCpf.setText("Cpf:");

        lblNome.setText("Nome:");

        lblSenha.setText("Senha de acesso:");

        lblData.setText("Data e hora do contrato:");

        lblSalario.setText("Valor do salário:");

        lblFuncao.setText("Função:");

        lblNivel.setText("Nível de acesso:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        cbxFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE:", "GARÇOM", "RECEPCIONISTA", "COZINHEIRO-CHEFE", "COZINHEIRO", "ENGENHEIRO DE SOFTWARE " }));

        cbxNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE:" }));
        cbxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNivelActionPerformed(evt);
            }
        });

        try {
            txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$#####,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao.setText("Descrição do nível:");

        txtDescricao.setText("\n\n\n\n\n");
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyReleased(evt);
            }
        });

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DIA:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaActionPerformed(evt);
            }
        });

        cbxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MÊS:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbxAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANO:", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        chbSenha.setText("Mostrar");
        chbSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroFuncionariosLayout = new javax.swing.GroupLayout(pnlCadastroFuncionarios);
        pnlCadastroFuncionarios.setLayout(pnlCadastroFuncionariosLayout);
        pnlCadastroFuncionariosLayout.setHorizontalGroup(
            pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                        .addComponent(lblNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao))
                    .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                        .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chbSenha))
                            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(lblSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(lblFuncao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblData)
                            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                                .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCadastroFuncionariosLayout.setVerticalGroup(
            pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addGap(5, 5, 5)
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFuncao)
                    .addComponent(cbxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroFuncionariosLayout.createSequentialGroup()
                        .addGroup(pnlCadastroFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNivel)
                            .addComponent(lblDescricao)
                            .addComponent(cbxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(txtDescricao)))
        );

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cpf:", "Nome:", "Data:", "Hora:", "Salário:", "Função:", "Nível:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionariosMouseClicked(evt);
            }
        });
        pnlTabelaFuncionarios.setViewportView(tblFuncionarios);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Confirmar.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Apagar.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/Pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar...");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemover)
                            .addComponent(btnInserir))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterar)
                            .addComponent(btnLimpar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnPesquisar)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFuncionariosLayout = new javax.swing.GroupLayout(pnlFuncionarios);
        pnlFuncionarios.setLayout(pnlFuncionariosLayout);
        pnlFuncionariosLayout.setHorizontalGroup(
            pnlFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionariosLayout.createSequentialGroup()
                .addGroup(pnlFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCadastroFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTabelaFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlFuncionariosLayout.setVerticalGroup(
            pnlFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionariosLayout.createSequentialGroup()
                .addComponent(pnlCadastroFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlTabelaFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed

    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try {
            if (campoVazio() == false) {
                registrarInsercao();
                String data = cbxAno.getSelectedItem().toString() + "/" + cbxMes.getSelectedItem().toString() + "/" + cbxDia.getSelectedItem().toString();
                String senha = String.valueOf(txtSenha.getPassword());
                f.setCpfFuncionario(txtCpf.getText());
                f.setNomeFuncionario(txtNome.getText());
                f.setSenhaFuncionario(senha);
                f.setDataContratoFuncionario(data);
                f.setHoraContratoFuncionario(txtHora.getText());
                f.setSalarioFuncionario(txtSalario.getText());
                f.setFuncaoFuncionario(cbxFuncao.getSelectedItem().toString());
                f.setNivelAdministracao(cbxNivel.getSelectedItem().toString());
                preencherFuncionarios();
                cif.inserir(f);
                JOptionPane.showMessageDialog(null, "Inserção feita com sucesso !", " ", JOptionPane.INFORMATION_MESSAGE);
                preencherTabela(null);
                limpar();
                registrarInsercao();
            } else {
                JOptionPane.showMessageDialog(null, "Há campos vazios que devem ser preenchidos", "Há campos vazios", JOptionPane.WARNING_MESSAGE);
                registrarTInsercao();
            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "Este cpf já existe!!!!", "Erro!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void cbxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNivelActionPerformed
        if (cbxNivel.getSelectedIndex() > 0) {
            Administracao adm = (Administracao) cbxNivel.getSelectedItem();
            txtDescricao.setText(adm.getDescricaoAdministracao());

        }
    }//GEN-LAST:event_cbxNivelActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        preencherFuncionarios();
        if (campoVazio() == false) {
            int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que irá alterar?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirma == 0) {
                String cpfFuncionario;
                if (tblFuncionarios.getSelectedRow() > -1) {
                    cpfFuncionario = tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 0).toString();
                } else {
                    cpfFuncionario = txtCpf.getText();
                }
                cif.alterar(f, cpfFuncionario);
                JOptionPane.showMessageDialog(null, "A alteração foi realizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                preencherTabela(null);
                limpar();
                registrarAlteracao();
            } else {
                preencherTabela(null);
                limpar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Há campos vazios", "Erro!", JOptionPane.ERROR_MESSAGE);
            registrarTAlteracao();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (txtCpf.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(null, "Você não adicionou nenhum cpf para remover", "Sem dados!", JOptionPane.ERROR_MESSAGE);
            registrarTRemocao();
        } else {
            int confirma;
            confirma = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja remover?\n Será permanente", "Confirmação:", JOptionPane.YES_NO_OPTION);
            if (confirma == 0) {
                registrarRemocao();
                cif.remover(txtCpf.getText());
                preencherTabela(null);
                limpar();
            } else {
                preencherTabela(null);
                limpar();
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (btnPesquisar.isSelected()) {
            preencherTabela(txtCpf.getText());
            btnPesquisar.setText("Cancelar");
        } else {
            btnPesquisar.setText("Pesquisar");
            preencherTabela(null);
            limpar();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        txtNome.setText(txtNome.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyReleased
        txtDescricao.setText(txtDescricao.getText().toUpperCase());
    }//GEN-LAST:event_txtDescricaoKeyReleased

    private void tblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMouseClicked
        if (tblFuncionarios.getSelectedRow() > -1) {
            String data = tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 2).toString();
            String[] parts = data.split("-");
            String dia = parts[2];
            String mes = parts[1];
            String ano = parts[0];
            String cpf = tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 0).toString();
            cbxDia.setSelectedItem(dia);
            cbxMes.setSelectedItem(mes);
            cbxAno.setSelectedItem(ano);
            txtCpf.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 0).toString());
            txtNome.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1).toString());
            ArrayList<Funcionario> funcionarios = cif.pesquisarSenha2(cpf);
            for (Funcionario f : funcionarios) {
            txtSenha.setText(f.getSenhaFuncionario());
            }
            txtHora.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 3).toString());
            txtSalario.setText(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 4).toString());
            cbxFuncao.setSelectedItem(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 5).toString());
            cbxNivel.setSelectedItem(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 6).toString());
            ArrayList<Administracao> administrando = cif.pesquisarNivelAdministracao();
            for (Administracao adm : administrando) {
                if (adm.getNivelAdministracao().equals(tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 6))) {
                    cbxNivel.setSelectedIndex(administrando.indexOf(adm) + 1);
                    habilitarBotoes(true);
                }
            }
        }
    }//GEN-LAST:event_tblFuncionariosMouseClicked

    private void cbxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cbxNivel.removeAllItems();
        cbxNivel.addItem("SELECIONE:");
        ArrayList administracao = cif.pesquisarNivelAdministracao();
        for (Object adm : administracao) {
            cbxNivel.addItem(adm);
        }
        limpar();
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        preencherTabela(null);
    }//GEN-LAST:event_formInternalFrameOpened

    private void chbSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbSenhaActionPerformed
    if(chbSenha.isSelected()){
            txtSenha.setEchoChar((char)0);
        }
        else{
            txtSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_chbSenhaActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        limpar();
    }//GEN-LAST:event_formInternalFrameClosed
    private void limpar() {
        txtCpf.setValue(null);
        txtNome.setText("");
        txtSenha.setText("");
        cbxDia.setSelectedItem("DIA:");
        cbxMes.setSelectedItem("MÊS:");
        cbxAno.setSelectedItem("ANO:");
        txtHora.setValue(null);
        txtSalario.setText(null);
        cbxFuncao.setSelectedItem("SELECIONE:");
        cbxNivel.setSelectedItem("SELECIONE:");
        txtDescricao.setText("");
        habilitarBotoes(false);
    }

    private boolean campoVazio() {
        boolean vazio = false;
        if (txtCpf.getText().equals("   .   .   -  ")
                || txtNome.getText() == null
                || txtSenha.getPassword() == null
                || cbxDia.getSelectedItem().equals("DIA:")
                || cbxMes.getSelectedItem().equals("MÊS:")
                || cbxAno.getSelectedItem().equals("ANO:")
                || txtHora.getText().equals("  :  :  ")
                || txtSalario.getText().equals("R$     ,  ")
                || cbxFuncao.getSelectedItem().equals("SELECIONE:")
                || txtDescricao.getText() == null) {
            vazio = true;
        }
        return vazio;
    }

    private void preencherTabela(String nomeFuncionario) {
        ArrayList<Funcionario> funcionariosTabe = cif.pesquisar(nomeFuncionario);
        DefaultTableModel modelo = (DefaultTableModel) tblFuncionarios.getModel();
        modelo.setNumRows(0);
        for (Funcionario f : funcionariosTabe) {
            modelo.addRow(new String[]{f.getCpfFuncionario(), f.getNomeFuncionario(), f.getDataContratoFuncionario(), f.getHoraContratoFuncionario(), f.getSalarioFuncionario(), f.getFuncaoFuncionario(), f.getNivelAdministracao()});
        }
        tblFuncionarios.setModel(modelo);

    }

    private void preencherFuncionarios() {
        String data = cbxAno.getSelectedItem().toString() + "/" + cbxMes.getSelectedItem().toString() + "/" + cbxDia.getSelectedItem().toString();
        String senha = String.valueOf(txtSenha.getPassword());
        f.setCpfFuncionario(txtCpf.getText());
        f.setNomeFuncionario(txtNome.getText());
        f.setSenhaFuncionario(senha);
        f.setDataContratoFuncionario(data);
        f.setHoraContratoFuncionario(txtHora.getText());
        f.setSalarioFuncionario(txtSalario.getText());
        f.setFuncaoFuncionario(cbxFuncao.getSelectedItem().toString());
        f.setNivelAdministracao(cbxNivel.getSelectedItem().toString());
    }

    private void habilitarBotoes(boolean habilitar) {
        if (habilitar) {
            btnRemover.setEnabled(true);
            btnAlterar.setEnabled(true);
        } else {
            btnRemover.setEnabled(false);
            btnAlterar.setEnabled(false);
        }
    }
    
    private void preencherRegistro() {
        r.setCpfCliente(null);
        r.setCpfAutor(FrmPrincipal.cpfAutor);
        r.setCpfFuncionario(f.getCpfFuncionario());
        r.setData(dh.getData());
        r.setHora(dh.getHora());
    }
    
    private void registrarAlteracao() {
        r.setAcaoRegistro("Tentativa de alteração bem-sucedida (Funcionário).");
        preencherRegistro();
        reg.registrar(r, dh);
    }
    
    private void registrarTAlteracao() {
        r.setAcaoRegistro("Tentativa de alteração fracassada (Funcionário).");
        preencherRegistro();
        reg.registrar(r, dh);
    }
    
    private void registrarRemocao() {
        r.setAcaoRegistro("Tentativa de remoção bem-sucedida (Funcionário).");
        preencherRegistro();
        reg.registrar(r, dh);
    }
    private void registrarTRemocao() {
        r.setAcaoRegistro("Tentativa de remoção fracassada (Funcionário).");
        preencherRegistro();
        reg.registrar(r, dh);
    }
    private void registrarInsercao() {
        r.setAcaoRegistro("Tentativa de inserção bem-sucedida (Funcionário).");
        preencherRegistro();
        reg.registrar(r, dh);
    }
    private void registrarTInsercao() {
        r.setAcaoRegistro("Tentativa de inserção fracassada (Funcionário).");
        preencherRegistro();
        reg.registrar(r, dh);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox cbxAno;
    private javax.swing.JComboBox cbxDia;
    private javax.swing.JComboBox cbxFuncao;
    private javax.swing.JComboBox cbxMes;
    private javax.swing.JComboBox cbxNivel;
    private javax.swing.JCheckBox chbSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlCadastroFuncionarios;
    private javax.swing.JPanel pnlFuncionarios;
    private javax.swing.JScrollPane pnlTabelaFuncionarios;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
